# Generated by Django 2.1.2 on 2019-01-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retman_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='introducing',
            field=models.BooleanField(default=False),
        ),
    ]
