# Generated by Django 2.0.6 on 2018-09-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retman_api', '0002_auto_20180924_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='expiration_date',
            field=models.DateField(null=True),
        ),
    ]
