# Generated by Django 2.0.6 on 2018-09-24 18:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('retman_api', '0003_auto_20180924_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='enrollment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='membership',
            name='expiration_date',
            field=models.DateTimeField(null=True),
        ),
    ]
