# Generated by Django 2.1.2 on 2020-02-02 16:10

from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import now


class Migration(migrations.Migration):

    dependencies = [
        ('retman_api', '0003_auto_20191203_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('visitations', models.IntegerField(default=0)),
                ('personal', models.IntegerField(default=0)),
                ('group', models.IntegerField(default=0)),
                ('months', models.FloatField(blank=True, default=1.0, null=True)),
                ('unlimited', models.BooleanField(default=False)),
                ('unlimited_visitations', models.BooleanField(default=False)),
                ('unlimited_personal', models.BooleanField(default=False)),
                ('unlimited_group', models.BooleanField(default=False)),
                ('cost', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='available_group',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='membership',
            name='available_personal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='membership',
            name='available_visitations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='membership',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='retman_api.MembershipType'),
        ),
    ]
