# Generated by Django 2.0.6 on 2018-09-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retman_api', '0004_auto_20180924_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='cost',
            field=models.IntegerField(default=2000),
        ),
    ]
