# Generated by Django 2.1.2 on 2020-02-02 16:18

from django.db import migrations
from django.utils.timezone import now


def make_initial_membership_type(apps, scheme_editor):
    Customer = apps.get_model('retman_api', 'Customer')
    Membership = apps.get_model('retman_api', 'Membership')
    for customer in Customer.objects.all():
        ct = customer.amount_of_available_visitations
        gt = customer.amount_of_available_group
        pt = customer.amount_of_available_personal
        if ct or gt or pt:
            Membership.objects.create(customer=customer, enrollment_date=now(), cost=0,
                                      available_visitations=ct, available_group=gt, available_personal=pt)


class Migration(migrations.Migration):

    dependencies = [
        ('retman_api', '0004_auto_20200202_1610'),
    ]

    operations = [
        migrations.RunPython(make_initial_membership_type, lambda *args, **kwargs: None),
    ]
