# Generated by Django 2.0.6 on 2018-09-26 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retman_api', '0005_membership_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='amount_of_available_personal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='membership',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='retman_api.Customer'),
        ),
        migrations.AlterField(
            model_name='visitation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custo', to='retman_api.Customer'),
        ),
    ]
