# Generated by Django 2.1.2 on 2020-02-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retman_api', '0005_create_memberships'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='amount_of_available_group',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='amount_of_available_personal',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='amount_of_available_visitations',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='who_advised',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='months',
        ),
        migrations.AlterField(
            model_name='membershiptype',
            name='months',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
