# Generated by Django 2.0.6 on 2018-09-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retman_api', '0006_auto_20180926_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitation',
            name='left_at',
            field=models.DateTimeField(null=True),
        ),
    ]
