# Generated by Django 2.1.2 on 2020-02-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retman_api', '0006_auto_20200202_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiptype',
            name='main_type',
            field=models.CharField(choices=[('VS', 'Обычные'), ('PT', 'Персональные тренировки'), ('GT', 'Групповые тренировки')], default='VS', max_length=10),
        ),
    ]
