# Generated by Django 2.0.6 on 2018-09-26 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retman_api', '0007_auto_20180926_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_customer', to='retman_api.Customer'),
        ),
        migrations.AlterField(
            model_name='visitation',
            name='key_number',
            field=models.IntegerField(null=True),
        ),
    ]
