# Generated by Django 2.0.6 on 2018-09-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retman_api', '0008_auto_20180926_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitation',
            name='key_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitation',
            name='left_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
