# Generated by Django 2.1.2 on 2020-03-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retman_api', '0010_auto_20200331_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='type',
            field=models.CharField(blank=True, choices=[('cash', 'Наличный'), ('card', 'Безналичный'), ('', '')], max_length=100, null=True),
        ),
    ]
