# Generated by Django 2.0.6 on 2018-09-29 19:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('retman_api', '0011_auto_20180928_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MS', 'Membership'), ('VS', 'Visitation'), ('PT', 'Personal training'), ('GT', 'Group training')], max_length=30)),
                ('value', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
