# Generated by Django 2.2.10 on 2020-05-05 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retman_api', '0011_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecognitionResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(blank=True, max_length=5, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('guid', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'permissions': [('can_see_stats', 'Can see statistics page')]},
        ),
        migrations.AlterField(
            model_name='membership',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='retman_api.MembershipType'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='retman_api.Service'),
        ),
    ]
