# Generated by Django 2.0.6 on 2018-09-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retman_api', '0012_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitation',
            name='type',
            field=models.CharField(choices=[('VS', 'Visitation'), ('PT', 'Personal training'), ('GT', 'Group training')], default='VS', max_length=30),
        ),
    ]
