# Generated by Django 2.0.6 on 2018-09-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retman_api', '0013_visitation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='amount_of_available_group',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('MS', 'Абонемент'), ('VS', 'Обычное'), ('PT', 'Персональная тренировка'), ('GT', 'Групповая тренировка')], max_length=30),
        ),
        migrations.AlterField(
            model_name='visitation',
            name='type',
            field=models.CharField(choices=[('VS', 'Обычное'), ('PT', 'Персональная тренировка'), ('GT', 'Групповая тренировка')], default='VS', max_length=30),
        ),
    ]
