# Generated by Django 2.2.10 on 2020-05-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retman_api', '0013_auto_20200517_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='full_name',
            field=models.CharField(blank=True, default='Новый тренер', max_length=500),
        ),
    ]
