# Generated by Django 2.2.10 on 2020-05-18 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retman_api', '0014_auto_20200517_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiptype',
            name='name',
            field=models.CharField(default='Новый тип абонемента', max_length=500),
        ),
        migrations.AlterField(
            model_name='visitation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_customer', to='retman_api.Customer'),
        ),
    ]
