# Generated by Django 2.0.6 on 2018-10-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retman_api', '0014_auto_20180930_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MS', 'Абонемент'), ('VS', 'Обычное'), ('PT', 'Персональная тренировка'), ('GT', 'Групповая тренировка')], max_length=30)),
                ('amount', models.IntegerField()),
                ('value', models.IntegerField()),
            ],
        ),
    ]
