# Generated by Django 2.0.6 on 2018-10-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retman_api', '0015_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='type',
            field=models.CharField(choices=[('MS', 'Абонемент'), ('VS', 'Обычное'), ('PT', 'Персональная тренировка'), ('GT', 'Групповая тренировка')], default='MS', max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='card_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='cost',
            unique_together={('type', 'amount')},
        ),
    ]
