# Generated by Django 2.0.6 on 2018-10-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retman_api', '0016_auto_20181003_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='passport',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
